title: The Daily Anomaly
url: https://news.promireclabs.work
baseurl: ""
permalink: pretty
markdown: kramdown
theme: null
plugins: []
sass: {}
defaults:
  - scope:
      path: "content"
    values:
      layout: "story"
  - scope:
      path: "editions"
    values:
      layout: "edition"
exclude:
  - content/2025-09-25
  - vendor
  - editions/2025-09-25.md
